# Welcome to Mago!
# For full documentation, see https://mago.carthage.software/tools/overview
php-version = "8.5.0"

[source]
paths = ["app/", "database/factories/", "database/seeders/", "tests/", "modules/"]
includes = ["vendor"]
excludes = []

[formatter]
print-width = 120
tab-width = 4
use-tabs = false

[linter]
integrations = ["psl", "laravel"]

[linter.rules]
# Best Practices
combine-consecutive-issets = { enabled = true }
final-controller = { enabled = true }
loop-does-not-iterate = { enabled = true }
no-sprintf-concat = { enabled = true }
prefer-anonymous-migration = { enabled = true }
prefer-first-class-callable = { enabled = false }
prefer-arrow-function = { enabled = true }
prefer-early-continue = { enabled = true }
prefer-static-closure = { enabled = true }
prefer-view-array = { enabled = true }
prefer-while-loop = { enabled = true }
psl-array-functions = { enabled = true }
psl-data-structures = { enabled = true }
psl-datetime = { enabled = false }
psl-math-functions = { enabled = true }
psl-output = { enabled = true }
psl-randomness-functions = { enabled = true }
psl-regex-functions = { enabled = true }
psl-sleep-functions = { enabled = true }
psl-string-functions = { enabled = true }
no-ini-set = { enabled = true }
middleware-in-routes = { enabled = true }
use-compound-assignment = { enabled = true }

# Clarity
literal-named-argument = { enabled = false }
no-shorthand-ternary = { enabled = false }
no-multi-assignments = { enabled = false }
no-nested-ternary = { enabled = true }
no-hash-emoji = { enabled = true }
no-variable-variable = { enabled = true }
no-empty = { enabled = true }
explicit-octal = { enabled = true }
str-contains = { enabled = true }
str-starts-with = { enabled = true }
tagged-fixme = { enabled = true }
tagged-todo = { enabled = true }
valid-docblock = { enabled = true }

# Consistency
array-style = { enabled = true }
block-statement = { enabled = true }
braced-string-interpolation = { enabled = true }
class-name = { enabled = true, psr = false }
constant-name = { enabled = false }
enum-name = { enabled = true }
lowercase-keyword = { enabled = true }
no-trailing-space = { enabled = true }
no-php-tag-terminator = { enabled = true }
no-hash-comment = { enabled = true }
no-alias-function = { enabled = true }
lowercase-type-hint = { enabled = true }
interface-name = { enabled = true, psr = false }
function-name = { enabled = true }
trait-name = { enabled = true, psr = false }

# Correctness
assert-description = { enabled = true }
no-empty-catch-clause = { enabled = true }
no-assign-in-condition = { enabled = false } # No, thanks. ~Erik
identity-comparison = { enabled = true }
invalid-open-tag = { enabled = true }
strict-behavior = { enabled = true }
strict-types = { enabled = true }

# Deprecation
optional-param-order = { enabled = true }
no-void-reference-return = { enabled = true }
no-underscore-class = { enabled = true }
explicit-nullable-param = { enabled = true }

# Maintainability
cyclomatic-complexity = { enabled = false }
excessive-nesting = { enabled = false }
excessive-parameter-list = { enabled = false }
halstead = { enabled = false }
kan-defect = { enabled = false }
no-goto = { enabled = true }
no-else-clause = { enabled = false }
no-boolean-flag-parameter = { enabled = true }
too-many-enum-cases = { enabled = false }
too-many-methods = { enabled = false }
too-many-properties = { enabled = false }

# Redundancy
no-redundant-write-visibility = { enabled = true }
no-redundant-string-concat = { enabled = true }
no-redundant-parentheses = { enabled = true }
no-redundant-method-override = { enabled = true }
no-redundant-nullsafe = { enabled = true }
no-redundant-math = { enabled = true }
no-redundant-label = { enabled = true }
no-redundant-final = { enabled = true }
no-redundant-readonly = { enabled = true }
no-redundant-file = { enabled = true }
no-redundant-continue = { enabled = true }
no-redundant-block = { enabled = true }
no-redundant-use = { enabled = true }
no-redundant-yield-from = { enabled = true }
no-self-assignment = { enabled = true }
no-protected-in-final = { enabled = true }
no-noop = { enabled = true }
no-empty-loop = { enabled = true }
no-empty-comment = { enabled = true }
no-closing-tag = { enabled = true }
constant-condition = { enabled = true }

# Safety
no-request-variable = { enabled = true }
no-shell-execute-string = { enabled = true }
no-global = { enabled = true }
no-ffi = { enabled = true }
no-eval = { enabled = true }
no-error-control-operator = { enabled = true }
no-unsafe-finally = { enabled = true }
no-request-all = { enabled = true }

# Security
disallowed-functions = { enabled = true }
no-debug-symbols = { enabled = true }
no-short-opening-tag = { enabled = true }
no-insecure-comparison = { enabled = true }
no-literal-password = { enabled = false }
tainted-data-to-sink = { enabled = true }
sensitive-parameter = { enabled = true }
require-preg-quote-delimiter = { enabled = true }

[analyzer]
find-unused-definitions = true
find-unused-expressions = false
analyze-dead-code = false
check-throws = false
allow-possibly-undefined-array-keys = true
perform-heuristic-checks = true
