name: tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          coverage: pcov

      - name: Install Dependencies
        uses: ramsey/composer-install@v3
        env:
          COMPOSER_AUTH: '{"github-oauth": {"github.com": "${{ secrets.GH_TOKEN_READ_REPOSITORIES }}"}}'

      - run: composer test

      - run: composer test:mutation
